name: Workflows with large secrets

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make script executable
        run: chmod +x ./.github/scripts/decrypt.sh

      - name: Decrypt large secret
        run: ./.github/scripts/decrypt.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
